import assert from "node:assert/strict";
import test from "node:test";
import { ALL_GOST_CURVES, createPrivateKey } from "@gostcrypto/signature";
import { OID, curveByOid, decodeOid, encodeOid, encodeSubjectPublicKeyInfo, extractSubjectPublicKeyInfo, parseCertificateEnvelope, parseSubjectPublicKeyInfo, publicKeyFromCertificate,publicKeyFromCertificateRequest, readDer, swapSignatureHalves, verifyCertificateRequestSignature,verifyCertificateRevocationListSignature,verifyCertificateSignature } from "@gostcrypto/asn1";

const certD2="MIIBJTCB06ADAgECAgEKMAoGCCqFAwcBAQMCMBIxEDAOBgNVBAMTB0V4YW1wbGUwIBcNMDEwMTAxMDAwMDAwWhgPMjA1MDEyMzEwMDAwMDBaMBIxEDAOBgNVBAMTB0V4YW1wbGUwXjAXBggqhQMHAQEBATALBgkqhQMHAQIBAQEDQwAEQHQnldS+6ITd8oUP7APqP68YROAdnaYLZFCTpV4m38OZePWWz01NDGzx0YlD2UST0WuewKFtUS0uEnzEaRpjGOKjEzARMA8GA1UdEwEB/wQFMAMBAf8wCgYIKoUDBwEBAwIDQQAUC02pEksJyw1c6Sjuh0JzoxASlJLsDik2njt5EkhXjB0OHaW+NHxvG1JWx66sIArWSsd6b1s6DglzGOeubudp";
const certD3="MIIBqjCCARagAwIBAgIBCzAKBggqhQMHAQEDAzASMRAwDgYDVQQDEwdFeGFtcGxlMCAXDTAxMDEwMTAwMDAwMFoYDzIwNTAxMjMxMDAwMDAwWjASMRAwDgYDVQQDEwdFeGFtcGxlMIGgMBcGCCqFAwcBAQECMAsGCSqFAwcBAgECAAOBhAAEgYDh7zDVLGEz3dmdHVxBRVz3302LTJJbvGmvFDPRVlhRWt0hRoUMMlxbgcEzvmVaqMTUQOe5io1ZSHsMdpa8xV0R7L53NqnsNX/y/TmTH04RTLjNo1knCsfw5/9D2UGUGeph/Sq3f12fY1I9O1CgT2PioM9Rt8E63CFWDwvUDMnHN6MTMBEwDwYDVR0TAQH/BAUwAwEB/zAKBggqhQMHAQEDAwOBgQBBVwPYkvGl8/aMQ1MYmn7iB7gLVjHvnUlSmk1rVCws+hWqLqzxH0cP3n2VSFaQPDX9j5Ve8wDZXHdTSnJKDu5wL4b6YKCBCRoj3XleHjxonuUSo8gu4NzCZDx47qj8rNNUklWEhrIPHJ7Bl8kGmYUCYMk7y82cXDMX4ZNE4XOuNg==";
const certD1="MIIBLTCB26ADAgECAgEKMAoGCCqFAwcBAQMCMBIxEDAOBgNVBAMTB0V4YW1wbGUwIBcNMDEwMTAxMDAwMDAwWhgPMjA1MDEyMzEwMDAwMDBaMBIxEDAOBgNVBAMTB0V4YW1wbGUwZjAfBggqhQMHAQEBATATBgcqhQMCAiMABggqhQMHAQECAgNDAARAC9hv5djbiWaPeJtOHbqFhcVQi0XsW1nYkG3bcOJJK3/ad/+HGhD73ydm0pPF0WSvuzx7lzpByIXRHXDWibTxJqMTMBEwDwYDVR0TAQH/BAUwAwEB/zAKBggqhQMHAQEDAgNBAE1T8BL+CBd2UH1Nm7gfAO/bTu/Uq4O6xLrPc1Fzz6gcQaoo0vGrFIKAzZ7Vb+2kGXQFNVSkJ2e4OtBD/TncBJM=";
const fromBase64=(value)=>Uint8Array.from(Buffer.from(value,"base64"));

test("DER OID codec handles GOST and multi-byte arcs",()=>{for(const oid of [OID.publicKey256,OID.paramSet256A,"1.2.840.113549.1.1.1","2.999.3"]){assert.equal(decodeOid(readDer(encodeOid(oid))),oid);}});
test("RFC 9215 certificate public keys parse and re-encode exactly",()=>{for(const [encoded,expectedCurve] of [[certD2,OID.paramSet256A],[certD3,OID.paramSet512Test]]){const spki=extractSubjectPublicKeyInfo(fromBase64(encoded));const parsed=parseSubjectPublicKeyInfo(spki);assert.equal(parsed.parameterSetOid,expectedCurve);assert.equal(parsed.publicKey.curve,curveByOid(expectedCurve));assert.deepEqual(encodeSubjectPublicKeyInfo(parsed.publicKey),spki);}});
test("SubjectPublicKeyInfo round-trips every named curve",()=>{for(const curve of ALL_GOST_CURVES){const key=createPrivateKey(curve,12345n);const parsed=parseSubjectPublicKeyInfo(encodeSubjectPublicKeyInfo(key.publicKey));assert.deepEqual(parsed.publicKey,key.publicKey,curve.name);}});
test("PKIX signature half swap is involutive",()=>{const value=Uint8Array.of(1,2,3,4);assert.deepEqual(swapSignatureHalves(value),Uint8Array.of(3,4,1,2));assert.deepEqual(swapSignatureHalves(swapSignatureHalves(value)),value);assert.throws(()=>swapSignatureHalves(Uint8Array.of(1,2,3)),/length/);});
test("malformed SPKI is rejected",()=>assert.throws(()=>parseSubjectPublicKeyInfo(Uint8Array.of(0x30,0)),/malformed/));
test("RFC 9215 self-signed certificate signatures verify",()=>{for(const encoded of [certD2,certD3]){const certificate=fromBase64(encoded),key=publicKeyFromCertificate(certificate),envelope=parseCertificateEnvelope(certificate);assert.ok([OID.signWithDigest256,OID.signWithDigest512].includes(envelope.signatureAlgorithmOid));assert.equal(verifyCertificateSignature(certificate,key),true);const damaged=Uint8Array.from(certificate);damaged[damaged.length-1]^=1;assert.equal(verifyCertificateSignature(damaged,key),false);}});
test("RFC 9215 legacy GOST 2001 certificate verifies",()=>{const certificate=fromBase64(certD1),key=publicKeyFromCertificate(certificate),envelope=parseCertificateEnvelope(certificate);assert.equal(envelope.signatureAlgorithmOid,OID.signWithDigest256);assert.equal(key.curve.name,"id-GostR3410-2001-TestParamSet");assert.equal(verifyCertificateSignature(certificate,key),true);});
const requests=["MIHTMIGBAgEAMBIxEDAOBgNVBAMTB0V4YW1wbGUwZjAfBggqhQMHAQEBATATBgcqhQMCAiMABggqhQMHAQECAgNDAARAC9hv5djbiWaPeJtOHbqFhcVQi0XsW1nYkG3bcOJJK3/ad/+HGhD73ydm0pPF0WSvuzx7lzpByIXRHXDWibTxJqAAMAoGCCqFAwcBAQMCA0EAaqqzjjXUqqUXlAMBeZEi2FVIT1efTLuW1jzf3zrMQypBqijS8asUgoDNntVv7aQZdAU1VKQnZ7g60EP9OdwEkw==","MIHKMHkCAQAwEjEQMA4GA1UEAxMHRXhhbXBsZTBeMBcGCCqFAwcBAQEBMAsGCSqFAwcBAgEBAQNDAARAdCeV1L7ohN3yhQ/sA+o/rxhE4B2dpgtkUJOlXibfw5l49ZbPTU0MbPHRiUPZRJPRa57AoW1RLS4SfMRpGmMY4qAAMAoGCCqFAwcBAQMCA0EAG9wqExdnm2YjL2PqFv98ZMyqua2FX8bhgJFmHbedSBIdDh2lvjR8bxtSVseurCAK1krHem9bOg4Jcxjnrm7naQ==","MIIBTzCBvAIBADASMRAwDgYDVQQDEwdFeGFtcGxlMIGgMBcGCCqFAwcBAQECMAsGCSqFAwcBAgECAAOBhAAEgYDh7zDVLGEz3dmdHVxBRVz3302LTJJbvGmvFDPRVlhRWt0hRoUMMlxbgcEzvmVaqMTUQOe5io1ZSHsMdpa8xV0R7L53NqnsNX/y/TmTH04RTLjNo1knCsfw5/9D2UGUGeph/Sq3f12fY1I9O1CgT2PioM9Rt8E63CFWDwvUDMnHN6AAMAoGCCqFAwcBAQMDA4GBAEM7HWzkClHx5XN+sWqixoOCmkBbnZEn4hJg/J1qwF2HvyTibEUnilwhkqdbqUmTq9YHTn/xvwP9L1OXr6HZRVgvhvpgoIEJGiPdeV4ePGie5RKjyC7g3MJkPHjuqPys01SSVYSGsg8cnsGXyQaZhQJgyTvLzZxcMxfhk0Thc642"];
test("RFC 9215 certificate requests verify",()=>{for(const encoded of requests){const request=fromBase64(encoded),key=publicKeyFromCertificateRequest(request);assert.equal(key.curve!==undefined,true);assert.equal(verifyCertificateRequestSignature(request),true);const damaged=Uint8Array.from(request);damaged[damaged.length-1]^=1;assert.equal(verifyCertificateRequestSignature(damaged),false);}});
const crlD2="MIGSMEECAQEwCgYIKoUDBwEBAwIwEjEQMA4GA1UEAxMHRXhhbXBsZRcNMTQwMTAxMDAwMDAwWhcNMTQwMTAyMDAwMDAwWjAKBggqhQMHAQEDAgNBABS9aAh8O5A8eqKLB/6y571v4JY/VjJnNZ9c2Oq0UFmtHQ4dpb40fG8bUlbHrqwgCtZKx3pvWzoOCXMY565u52k=";
test("RFC 9215 CRL signature verifies",()=>{const certificate=fromBase64(certD2),crl=fromBase64(crlD2),key=publicKeyFromCertificate(certificate);assert.equal(verifyCertificateRevocationListSignature(crl,key),true);crl[crl.length-1]^=1;assert.equal(verifyCertificateRevocationListSignature(crl,key),false);});
