import { OID, decodeOid, encodeDer, encodeOctetString, encodeOid, encodeSequence, encodeSubjectPublicKeyInfo, extractSubjectPublicKeyInfo, parseSubjectPublicKeyInfo, publicKeyFromCertificate, readDer, readDerChildren, type DerElement } from "@gostcrypto/asn1";
import { streebog256, streebog512 } from "@gostcrypto/hash";
import { unwrapCryptoPro, wrapCryptoPro } from "@gostcrypto/keywrap";
import { Gost28147MeshedCfb, paramCryptoProA, paramCryptoProB, paramCryptoProC, paramCryptoProD, paramZ, type Gost28147SBox } from "@gostcrypto/legacy-gost28147";
import { gost341194, gost341194Test } from "@gostcrypto/legacy-gost341194";
import { decodePkixSignature, encodePkixSignature, generatePrivateKey, signDigest, verifyDigest, type GostPrivateKey, type RandomFill } from "@gostcrypto/signature";
import { deriveVkoKek256, ukmFromBytes } from "@gostcrypto/vko";

export const CMS_OID=Object.freeze({signedData:"1.2.840.113549.1.7.2",envelopedData:"1.2.840.113549.1.7.3",data:"1.2.840.113549.1.7.1",contentType:"1.2.840.113549.1.9.3",messageDigest:"1.2.840.113549.1.9.4",signingTime:"1.2.840.113549.1.9.5",signingCertificate:"1.2.840.113549.1.9.16.2.12",signingCertificateV2:"1.2.840.113549.1.9.16.2.47",signatureTimeStamp:"1.2.840.113549.1.9.16.2.14",tstInfo:"1.2.840.113549.1.9.16.1.4"});

export type CmsErrorCode="MALFORMED"|"UNSUPPORTED"|"NO_CERTIFICATE"|"NO_CONTENT"|"DIGEST_MISMATCH"|"SIGNATURE"|"KEY_MISMATCH"|"SIGNING_CERTIFICATE"|"RECIPIENTS"|"NO_RECIPIENT"|"TIMESTAMP_IMPRINT"|"TIMESTAMP_STATUS"|"NO_TIMESTAMP";
export class CmsError extends Error {constructor(public readonly code:CmsErrorCode,message:string){super(message);this.name="CmsError";}}
const fail=(code:CmsErrorCode,message:string):CmsError=>new CmsError(code,message);
const concat=(...parts:readonly Uint8Array[]):Uint8Array=>{const result=new Uint8Array(parts.reduce((sum,part)=>sum+part.length,0));let offset=0;for(const part of parts){result.set(part,offset);offset+=part.length;}return result;};
function compare(left:Uint8Array,right:Uint8Array):number {const length=Math.min(left.length,right.length);for(let i=0;i<length;i+=1)if(left[i]!==right[i])return left[i]!-right[i]!;return left.length-right.length;}
function equal(left:Uint8Array,right:Uint8Array):boolean {if(left.length!==right.length)return false;let difference=0;for(let i=0;i<left.length;i+=1)difference|=left[i]!^right[i]!;return difference===0;}
function derSet(tag:number,elements:readonly Uint8Array[]):Uint8Array{return encodeDer(tag,concat(...[...elements].sort(compare)));}
function integer(value:number):Uint8Array {const bytes:number[]=[];do{bytes.unshift(value&255);value=Math.floor(value/256);}while(value>0);if((bytes[0]!&128)!==0)bytes.unshift(0);return encodeDer(0x02,Uint8Array.from(bytes));}
function sequence(der:Uint8Array):DerElement[]{const outer=readDer(der);if(outer.tag!==0x30||outer.end!==der.length)throw fail("MALFORMED","malformed CMS structure");return readDerChildren(outer.content);}
function algorithmOid(element:DerElement):string {if(element.tag!==0x30)throw fail("MALFORMED","malformed AlgorithmIdentifier");const fields=readDerChildren(element.content);if(fields.length<1||fields[0]!.tag!==0x06)throw fail("MALFORMED","malformed AlgorithmIdentifier");return decodeOid(fields[0]!);}
function digest(oid:string,data:Uint8Array,parameters?:DerElement):Uint8Array {if(oid===OID.digest256)return streebog256(data);if(oid===OID.digest512)return streebog512(data);if(oid===OID.digest94){if(parameters?.tag===0x06&&decodeOid(parameters)===OID.hashParamTest)return gost341194Test(data);return gost341194(data);}throw fail("UNSUPPORTED",`unsupported digest algorithm ${oid}`);}
function digestForKey(key:GostPrivateKey,data:Uint8Array):Uint8Array{return key.curve.size===32?streebog256(data):streebog512(data);}
function algorithm(oid:string):Uint8Array{return encodeSequence(encodeOid(oid));}
function attribute(oid:string,value:Uint8Array):Uint8Array{return encodeSequence(encodeOid(oid),derSet(0x31,[value]));}

interface CertificateMeta {readonly der:Uint8Array;readonly issuer:Uint8Array;readonly serial:Uint8Array;}
function certificateMeta(der:Uint8Array):CertificateMeta {const certificate=sequence(der);if(certificate.length!==3||certificate[0]!.tag!==0x30)throw fail("MALFORMED","malformed certificate");const tbs=readDerChildren(certificate[0]!.content),offset=tbs[0]?.tag===0xa0?1:0,serial=tbs[offset],issuer=tbs[offset+2];if(serial?.tag!==0x02||issuer?.tag!==0x30)throw fail("MALFORMED","malformed certificate identity");return{der:Uint8Array.from(der),issuer:Uint8Array.from(issuer.full),serial:Uint8Array.from(serial.full)};}

interface ParsedAttribute {readonly oid:string;readonly values:DerElement[];readonly full:Uint8Array;}
function parseAttributes(raw:Uint8Array):ParsedAttribute[]{return readDerChildren(raw).map((element)=>{if(element.tag!==0x30)throw fail("MALFORMED","malformed signed attribute");const fields=readDerChildren(element.content);if(fields.length!==2||fields[0]!.tag!==0x06||fields[1]!.tag!==0x31)throw fail("MALFORMED","malformed signed attribute");return{oid:decodeOid(fields[0]!),values:readDerChildren(fields[1]!.content),full:Uint8Array.from(element.full)};});}
function parseTime(element:DerElement|undefined):Date|undefined {if(element===undefined||(element.tag!==0x17&&element.tag!==0x18))return undefined;const text=new TextDecoder("ascii").decode(element.content),match=element.tag===0x17?/^(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})Z$/.exec(text):/^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})(?:\.(\d+))?Z$/.exec(text);if(match===null)return undefined;const year=element.tag===0x17?(Number(match[1])>=50?1900:2000)+Number(match[1]):Number(match[1]),millis=match[7]===undefined?0:Math.floor(Number(`0.${match[7]}`)*1000),date=new Date(Date.UTC(year,Number(match[2])-1,Number(match[3]),Number(match[4]),Number(match[5]),Number(match[6]),millis));return Number.isNaN(date.valueOf())?undefined:date;}
function encodeTime(date:Date):Uint8Array {if(Number.isNaN(date.valueOf()))throw new RangeError("invalid signing time");const year=date.getUTCFullYear(),two=(value:number)=>String(value).padStart(2,"0"),suffix=`${two(date.getUTCMonth()+1)}${two(date.getUTCDate())}${two(date.getUTCHours())}${two(date.getUTCMinutes())}${two(date.getUTCSeconds())}Z`;return encodeDer(year>=1950&&year<2050?0x17:0x18,new TextEncoder().encode(year>=1950&&year<2050?`${two(year%100)}${suffix}`:`${String(year).padStart(4,"0")}${suffix}`));}

function signingCertificateAttribute(certificate:CertificateMeta,digestOid:string):Uint8Array {const certHash=digest(digestOid,certificate.der),issuerSerial=encodeSequence(encodeSequence(encodeDer(0xa4,certificate.issuer)),certificate.serial),certId=encodeSequence(algorithm(digestOid),encodeOctetString(certHash),issuerSerial),value=encodeSequence(encodeSequence(certId));return attribute(CMS_OID.signingCertificateV2,value);}
function verifySigningCertificate(attrs:readonly ParsedAttribute[],certificate:CertificateMeta):void {const attr=attrs.find((item)=>item.oid===CMS_OID.signingCertificateV2);if(attr===undefined){if(attrs.some((item)=>item.oid===CMS_OID.signingCertificate))throw fail("UNSUPPORTED","SHA-1 signingCertificate validation is unavailable");return;}const value=attr.values[0];if(value?.tag!==0x30)throw fail("MALFORMED","malformed signingCertificateV2");const outer=readDerChildren(value.content),certs=outer[0];if(certs?.tag!==0x30)throw fail("MALFORMED","malformed signingCertificateV2");const ids=readDerChildren(certs.content),fields=ids[0]?.tag===0x30?readDerChildren(ids[0].content):[];if(fields.length<1)throw fail("MALFORMED","malformed signingCertificateV2");let index=0,oid="2.16.840.1.101.3.4.2.1";if(fields[index]?.tag===0x30){oid=algorithmOid(fields[index]!);index+=1;}const hash=fields[index];if(hash?.tag!==0x04)throw fail("MALFORMED","malformed signingCertificateV2");if(oid!==OID.digest256&&oid!==OID.digest512&&oid!==OID.digest94)throw fail("UNSUPPORTED",`unsupported ESS digest ${oid}`);if(!equal(hash.content,digest(oid,certificate.der)))throw fail("SIGNING_CERTIFICATE","signingCertificateV2 does not match signer certificate");}

interface InternalSigner {readonly sid:DerElement;readonly digestAlgorithm:DerElement;readonly signedAttributes?:DerElement;readonly signatureAlgorithm:DerElement;readonly signature:Uint8Array;readonly unsignedAttributes?:DerElement;}
export class CmsSigner {
  readonly digestAlgorithmOid:string;readonly signatureAlgorithmOid:string;readonly signingTime?:Date;readonly hasSigningCertificate:boolean;
  constructor(public certificate:Uint8Array|undefined,private readonly internal:InternalSigner){this.digestAlgorithmOid=algorithmOid(internal.digestAlgorithm);this.signatureAlgorithmOid=algorithmOid(internal.signatureAlgorithm);const attrs=internal.signedAttributes===undefined?[]:parseAttributes(internal.signedAttributes.content);this.signingTime=parseTime(attrs.find((item)=>item.oid===CMS_OID.signingTime)?.values[0]!);this.hasSigningCertificate=attrs.some((item)=>item.oid===CMS_OID.signingCertificateV2||item.oid===CMS_OID.signingCertificate);}
  get signatureValue():Uint8Array{return Uint8Array.from(this.internal.signature);}
  timestamps():CmsTimestamp[]{if(this.internal.unsignedAttributes===undefined)return[];const result:CmsTimestamp[]=[];for(const attr of parseAttributes(this.internal.unsignedAttributes.content)){if(attr.oid===CMS_OID.signatureTimeStamp)for(const value of attr.values)result.push(parseTimestampToken(value.full));}return result;}
  verifyTimestamps():number {const values=this.timestamps();for(const timestamp of values)timestamp.verify(this.signatureValue);return values.length;}
  _info():InternalSigner{return this.internal;}
}

export class CmsSignedData {
  constructor(public readonly detached:boolean,public readonly content:Uint8Array,public readonly contentType:string,public readonly certificates:Uint8Array[],public readonly signers:CmsSigner[]){}
  verify(content?:Uint8Array):void {for(const signer of this.signers)this.verifySigner(signer,content);}
  verifySigner(signer:CmsSigner,externalContent?:Uint8Array):void {const data=externalContent??(this.detached?undefined:this.content);if(data===undefined)throw fail("NO_CONTENT","detached CMS content was not provided");if(signer.certificate===undefined)throw fail("NO_CERTIFICATE","signer certificate was not found");const info=signer._info(),publicKey=publicKeyFromCertificate(signer.certificate),contentDigest=digest(signer.digestAlgorithmOid,data,readDerChildren(info.digestAlgorithm.content)[1]);let signedDigest=contentDigest;
    if(info.signedAttributes!==undefined){const attrs=parseAttributes(info.signedAttributes.content),messageDigest=attrs.find((item)=>item.oid===CMS_OID.messageDigest)?.values[0];if(messageDigest?.tag!==0x04)throw fail("MALFORMED","CMS messageDigest attribute is missing");if(!equal(messageDigest.content,contentDigest))throw fail("DIGEST_MISMATCH","CMS content digest does not match");const signed=Uint8Array.from(info.signedAttributes.full);signed[0]=0x31;signedDigest=digest(signer.digestAlgorithmOid,signed);verifySigningCertificate(attrs,certificateMeta(signer.certificate));}
    try{if(!verifyDigest(publicKey,signedDigest,decodePkixSignature(publicKey.curve,info.signature)))throw fail("SIGNATURE","CMS signature verification failed");}catch(error){if(error instanceof CmsError)throw error;throw fail("MALFORMED","malformed CMS signature");}
  }
}

function findCertificate(sid:DerElement,certificates:readonly CertificateMeta[]):Uint8Array|undefined {if(sid.tag===0x30){const fields=readDerChildren(sid.content);if(fields.length===2){const match=certificates.find((certificate)=>equal(certificate.issuer,fields[0]!.full)&&equal(certificate.serial,fields[1]!.full));if(match!==undefined)return match.der;}}return certificates.length===1?certificates[0]!.der:undefined;}
function parseSigner(element:DerElement,certificates:readonly CertificateMeta[]):CmsSigner {if(element.tag!==0x30)throw fail("MALFORMED","malformed SignerInfo");const fields=readDerChildren(element.content);let index=0;if(fields[index++]?.tag!==0x02)throw fail("MALFORMED","malformed SignerInfo");const sid=fields[index++],digestAlgorithm=fields[index++];if(sid===undefined||digestAlgorithm?.tag!==0x30)throw fail("MALFORMED","malformed SignerInfo");const signedAttributes=fields[index]?.tag===0xa0?fields[index++]:undefined,signatureAlgorithm=fields[index++],signature=fields[index++],unsignedAttributes=fields[index]?.tag===0xa1?fields[index++]:undefined;if(signatureAlgorithm?.tag!==0x30||signature?.tag!==0x04||index!==fields.length)throw fail("MALFORMED","malformed SignerInfo");return new CmsSigner(findCertificate(sid,certificates),{sid,digestAlgorithm,signedAttributes,signatureAlgorithm,signature:Uint8Array.from(signature.content),unsignedAttributes});}

export function parseSignedData(der:Uint8Array):CmsSignedData {try{const outer=sequence(der);if(outer.length!==2||decodeOid(outer[0]!)!==CMS_OID.signedData||outer[1]!.tag!==0xa0)throw fail("UNSUPPORTED","CMS content is not SignedData");const fields=sequence(outer[1]!.content);if(fields.length<4||fields[0]!.tag!==0x02||fields[1]!.tag!==0x31||fields[2]!.tag!==0x30)throw fail("MALFORMED","malformed SignedData");const encap=readDerChildren(fields[2]!.content);if(encap.length<1||encap.length>2||encap[0]!.tag!==0x06||(encap[1]!==undefined&&encap[1].tag!==0xa0))throw fail("MALFORMED","malformed EncapsulatedContentInfo");const detached=encap[1]===undefined,content=detached?new Uint8Array():(()=>{const item=readDer(encap[1]!.content);if(item.tag!==0x04||item.end!==encap[1]!.content.length)throw fail("MALFORMED","malformed encapsulated content");return Uint8Array.from(item.content);})();let index=3;const certificates:CertificateMeta[]=[];if(fields[index]?.tag===0xa0){for(const item of readDerChildren(fields[index++]!.content)){try{certificates.push(certificateMeta(item.full));}catch{/* CMS permits unsupported certificate choices. */}}}if(fields[index]?.tag===0xa1)index+=1;const signerSet=fields[index];if(signerSet?.tag!==0x31||index!==fields.length-1)throw fail("MALFORMED","malformed signerInfos");const signers=readDerChildren(signerSet.content).map((item)=>parseSigner(item,certificates));if(signers.length===0)throw fail("MALFORMED","SignedData has no signers");return new CmsSignedData(detached,content,decodeOid(encap[0]!),certificates.map((item)=>item.der),signers);}catch(error){if(error instanceof CmsError)throw error;throw fail("MALFORMED","malformed CMS SignedData");}}

export type CmsTimestamper=(signatureValue:Uint8Array)=>Uint8Array;
export interface SignCmsOptions {readonly detached?:boolean;readonly signingTime?:Date;readonly certificates?:readonly Uint8Array[];readonly contentType?:string;readonly noSigningCertificate?:boolean;readonly timestamp?:CmsTimestamper;readonly fillRandom?:RandomFill;}
export function signCms(content:Uint8Array,certificateDer:Uint8Array,privateKey:GostPrivateKey,options:SignCmsOptions={}):Uint8Array {const certificate=certificateMeta(certificateDer),certPublicKey=publicKeyFromCertificate(certificateDer);if(certPublicKey.x!==privateKey.publicKey.x||certPublicKey.y!==privateKey.publicKey.y||certPublicKey.curve.size!==privateKey.curve.size)throw fail("KEY_MISMATCH","certificate does not match private key");const digestOid=privateKey.curve.size===32?OID.digest256:OID.digest512,signatureOid=privateKey.curve.size===32?OID.signWithDigest256:OID.signWithDigest512,contentType=options.contentType??CMS_OID.data;
  const attrs=[attribute(CMS_OID.contentType,encodeOid(contentType)),attribute(CMS_OID.messageDigest,encodeOctetString(digestForKey(privateKey,content)))];if(options.signingTime!==undefined)attrs.push(attribute(CMS_OID.signingTime,encodeTime(options.signingTime)));if(options.noSigningCertificate!==true)attrs.push(signingCertificateAttribute(certificate,digestOid));const signedAttrs=derSet(0x31,attrs),signature=encodePkixSignature(privateKey.curve,signDigest(privateKey,digestForKey(privateKey,signedAttrs),options.fillRandom)),implicitAttrs=Uint8Array.from(signedAttrs);implicitAttrs[0]=0xa0;
  let unsigned:Uint8Array|undefined;if(options.timestamp!==undefined){const token=options.timestamp(Uint8Array.from(signature));if(token.length===0)throw fail("NO_TIMESTAMP","timestamp service returned no token");parseTimestampToken(token).verify(signature);unsigned=derSet(0xa1,[attribute(CMS_OID.signatureTimeStamp,token)]);}const signerInfo=encodeSequence(integer(1),encodeSequence(certificate.issuer,certificate.serial),algorithm(digestOid),implicitAttrs,algorithm(signatureOid),encodeOctetString(signature),...(unsigned===undefined?[]:[unsigned]));const certificateList=[certificate.der,...(options.certificates??[]).filter((item)=>!equal(item,certificate.der))];const encap=encodeSequence(encodeOid(contentType),...(options.detached===true?[]:[encodeDer(0xa0,encodeOctetString(content))]));const signedData=encodeSequence(integer(1),derSet(0x31,[algorithm(digestOid)]),encap,derSet(0xa0,certificateList),derSet(0x31,[signerInfo]));return encodeSequence(encodeOid(CMS_OID.signedData),encodeDer(0xa0,signedData));}

const sboxFactories=new Map<string,()=>Gost28147SBox>([[OID.cipherParamZ,paramZ],[OID.cipherCryptoProA,paramCryptoProA],[OID.cipherCryptoProB,paramCryptoProB],[OID.cipherCryptoProC,paramCryptoProC],[OID.cipherCryptoProD,paramCryptoProD]]);
function randomBytes(size:number,fill?:RandomFill):Uint8Array {const output=new Uint8Array(size);if(fill!==undefined)fill(output);else{if(globalThis.crypto===undefined)throw new Error("Web Crypto getRandomValues is unavailable");globalThis.crypto.getRandomValues(output);}return output;}
function sboxFor(oid:string):Gost28147SBox {const factory=sboxFactories.get(oid);if(factory===undefined)throw fail("UNSUPPORTED",`unsupported GOST 28147 parameter set ${oid}`);return factory();}

interface RecipientTransport {readonly encryptionParamSet:string;readonly ephemeralPublicKey:Uint8Array;readonly ukm:Uint8Array;readonly encryptedKey:Uint8Array;readonly mac:Uint8Array;}
export class CmsRecipient {constructor(public readonly issuer:Uint8Array,public readonly serial:Uint8Array,private readonly transport:RecipientTransport){}_transport():RecipientTransport{return this.transport;}}
export class CmsEnvelopedData {
  constructor(public readonly recipients:CmsRecipient[],public readonly contentType:string,private readonly encrypted:Uint8Array,private readonly iv:Uint8Array,private readonly parameterSetOid:string){}
  decrypt(privateKey:GostPrivateKey,certificateDer?:Uint8Array):Uint8Array {const identity=certificateDer===undefined?undefined:certificateMeta(certificateDer);for(const recipient of this.recipients){if(identity!==undefined&&(!equal(identity.issuer,recipient.issuer)||!equal(identity.serial,recipient.serial)))continue;try{const transport=recipient._transport();if(transport.ukm.length!==8||transport.encryptedKey.length!==32||transport.mac.length!==4)throw fail("MALFORMED","malformed GOST key transport");const ephemeral=parseSubjectPublicKeyInfo(transport.ephemeralPublicKey).publicKey,kek=deriveVkoKek256(privateKey,ephemeral,ukmFromBytes(transport.ukm)),wrapped=concat(transport.ukm,transport.encryptedKey,transport.mac),cek=unwrapCryptoPro(kek,wrapped,sboxFor(transport.encryptionParamSet));if(this.encrypted.length===0)throw fail("NO_CONTENT","CMS encrypted content is absent");return new Gost28147MeshedCfb(cek,sboxFor(this.parameterSetOid),this.iv,true).update(this.encrypted);}catch(error){if(identity!==undefined){if(error instanceof CmsError)throw error;throw fail("NO_RECIPIENT","recipient key cannot decrypt CMS content");}}
    }throw fail("NO_RECIPIENT","recipient was not found in CMS EnvelopedData");}
}

function parseTransport(der:Uint8Array):RecipientTransport {const fields=sequence(der),session=fields[0],parameters=fields[1];if(session?.tag!==0x30||parameters?.tag!==0xa0||fields.length!==2)throw fail("MALFORMED","malformed GOST key transport");const sessionFields=readDerChildren(session.content),paramFields=readDerChildren(parameters.content);if(sessionFields.length<2||sessionFields[0]!.tag!==0x04||sessionFields.at(-1)!.tag!==0x04||paramFields.length!==3||paramFields[0]!.tag!==0x06||paramFields[1]!.tag!==0xa0||paramFields[2]!.tag!==0x04)throw fail("MALFORMED","malformed GOST key transport");return{encryptedKey:Uint8Array.from(sessionFields[0]!.content),mac:Uint8Array.from(sessionFields.at(-1)!.content),encryptionParamSet:decodeOid(paramFields[0]!),ephemeralPublicKey:encodeDer(0x30,paramFields[1]!.content),ukm:Uint8Array.from(paramFields[2]!.content)};}
function parseRecipient(element:DerElement):CmsRecipient|undefined {try{if(element.tag!==0x30)return undefined;const fields=readDerChildren(element.content);if(fields.length!==4||fields[0]!.tag!==0x02||fields[1]!.tag!==0x30||fields[2]!.tag!==0x30||fields[3]!.tag!==0x04)return undefined;const sid=readDerChildren(fields[1]!.content);if(sid.length!==2||sid[0]!.tag!==0x30||sid[1]!.tag!==0x02)return undefined;return new CmsRecipient(Uint8Array.from(sid[0]!.full),Uint8Array.from(sid[1]!.full),parseTransport(fields[3]!.content));}catch{return undefined;}}
export function parseEnvelopedData(der:Uint8Array):CmsEnvelopedData {try{const outer=sequence(der);if(outer.length!==2||decodeOid(outer[0]!)!==CMS_OID.envelopedData||outer[1]!.tag!==0xa0)throw fail("UNSUPPORTED","CMS content is not EnvelopedData");const fields=sequence(outer[1]!.content);let index=0;if(fields[index++]?.tag!==0x02)throw fail("MALFORMED","malformed EnvelopedData");if(fields[index]?.tag===0xa0)index+=1;const recipientSet=fields[index++],eci=fields[index++];if(recipientSet?.tag!==0x31||eci?.tag!==0x30)throw fail("MALFORMED","malformed EnvelopedData");const content=readDerChildren(eci.content);if(content.length<2||content.length>3||content[0]!.tag!==0x06||content[1]!.tag!==0x30||(content[2]!==undefined&&content[2].tag!==0x80))throw fail("MALFORMED","malformed EncryptedContentInfo");const encryptionAlgorithm=readDerChildren(content[1]!.content);if(encryptionAlgorithm.length!==2||decodeOid(encryptionAlgorithm[0]!)!==OID.cipher28147||encryptionAlgorithm[1]!.tag!==0x30)throw fail("UNSUPPORTED","unsupported CMS content encryption");const parameters=readDerChildren(encryptionAlgorithm[1]!.content);if(parameters.length!==2||parameters[0]!.tag!==0x04||parameters[0]!.content.length!==8||parameters[1]!.tag!==0x06)throw fail("MALFORMED","malformed GOST 28147 parameters");const parameterSetOid=decodeOid(parameters[1]!);sboxFor(parameterSetOid);const recipients=readDerChildren(recipientSet.content).map(parseRecipient).filter((item):item is CmsRecipient=>item!==undefined);if(recipients.length===0)throw fail("MALFORMED","EnvelopedData has no supported recipients");return new CmsEnvelopedData(recipients,decodeOid(content[0]!),content[2]===undefined?new Uint8Array():Uint8Array.from(content[2].content),Uint8Array.from(parameters[0]!.content),parameterSetOid);}catch(error){if(error instanceof CmsError)throw error;throw fail("MALFORMED","malformed CMS EnvelopedData");}}

export interface EncryptCmsOptions {readonly parameterSetOid?:string;readonly contentType?:string;readonly fillRandom?:RandomFill;}
function wrapForRecipient(cek:Uint8Array,certificateDer:Uint8Array,parameterSetOid:string,fill?:RandomFill):Uint8Array {const certificate=certificateMeta(certificateDer),recipientSpki=sequence(extractSubjectPublicKeyInfo(certificateDer)),publicKey=publicKeyFromCertificate(certificateDer),ephemeral=generatePrivateKey(publicKey.curve,fill),ukm=randomBytes(8,fill),kek=deriveVkoKek256(ephemeral,publicKey,ukmFromBytes(ukm)),wrapped=wrapCryptoPro(kek,ukm,cek,sboxFor(parameterSetOid)),ephemeralSpki=sequence(encodeSubjectPublicKeyInfo(ephemeral.publicKey));const implicitSpki=encodeDer(0xa0,concat(recipientSpki[0]!.full,ephemeralSpki[1]!.full)),transportParameters=encodeDer(0xa0,concat(encodeOid(parameterSetOid),implicitSpki,encodeOctetString(ukm))),session=encodeSequence(encodeOctetString(wrapped.subarray(8,40)),encodeOctetString(wrapped.subarray(40))),transport=encodeSequence(session,transportParameters),sid=encodeSequence(certificate.issuer,certificate.serial);return encodeSequence(integer(0),sid,recipientSpki[0]!.full,encodeOctetString(transport));}
export function encryptCms(content:Uint8Array,recipientCertificates:readonly Uint8Array[],options:EncryptCmsOptions={}):Uint8Array {if(recipientCertificates.length===0)throw fail("RECIPIENTS","CMS recipient list is empty");const parameterSetOid=options.parameterSetOid??OID.cipherCryptoProA,sbox=sboxFor(parameterSetOid),cek=randomBytes(32,options.fillRandom),iv=randomBytes(8,options.fillRandom),encrypted=new Gost28147MeshedCfb(cek,sbox,iv).update(content),recipients=recipientCertificates.map((certificate)=>wrapForRecipient(cek,certificate,parameterSetOid,options.fillRandom)),encryptionAlgorithm=encodeSequence(encodeOid(OID.cipher28147),encodeSequence(encodeOctetString(iv),encodeOid(parameterSetOid))),eci=encodeSequence(encodeOid(options.contentType??CMS_OID.data),encryptionAlgorithm,encodeDer(0x80,encrypted)),enveloped=encodeSequence(integer(0),derSet(0x31,recipients),eci);return encodeSequence(encodeOid(CMS_OID.envelopedData),encodeDer(0xa0,enveloped));}

function encodeBigInteger(value:bigint):Uint8Array {if(value<0n)throw new RangeError("negative ASN.1 integers are unsupported");const bytes:number[]=[];do{bytes.unshift(Number(value&255n));value>>=8n;}while(value>0n);if((bytes[0]!&128)!==0)bytes.unshift(0);return encodeDer(0x02,Uint8Array.from(bytes));}
function decodeBigInteger(element:DerElement):bigint {if(element.tag!==0x02||element.content.length===0||(element.content[0]!&128)!==0)throw fail("MALFORMED","malformed ASN.1 integer");let result=0n;for(const byte of element.content)result=(result<<8n)|BigInt(byte);return result;}
function generalizedTime(date:Date):Uint8Array {if(Number.isNaN(date.valueOf()))throw new RangeError("invalid timestamp time");const part=(value:number,size=2)=>String(value).padStart(size,"0"),text=`${part(date.getUTCFullYear(),4)}${part(date.getUTCMonth()+1)}${part(date.getUTCDate())}${part(date.getUTCHours())}${part(date.getUTCMinutes())}${part(date.getUTCSeconds())}Z`;return encodeDer(0x18,new TextEncoder().encode(text));}
interface TimestampImprint {readonly algorithmOid:string;readonly hashedMessage:Uint8Array;readonly algorithm:DerElement;}
function parseImprint(element:DerElement):TimestampImprint {if(element.tag!==0x30)throw fail("MALFORMED","malformed timestamp message imprint");const fields=readDerChildren(element.content);if(fields.length!==2||fields[0]!.tag!==0x30||fields[1]!.tag!==0x04)throw fail("MALFORMED","malformed timestamp message imprint");return{algorithmOid:algorithmOid(fields[0]!),hashedMessage:Uint8Array.from(fields[1]!.content),algorithm:fields[0]!};}

export class CmsTimestamp {
  constructor(public readonly genTime:Date,public readonly accuracyMilliseconds:number,public readonly serialNumber:bigint,public readonly policy:string,public readonly nonce:bigint|undefined,public readonly certificates:Uint8Array[],public readonly signers:CmsSigner[],private readonly token:CmsSignedData,private readonly imprint:TimestampImprint,private readonly encoded:Uint8Array){}
  raw():Uint8Array{return Uint8Array.from(this.encoded);}
  verify(data:Uint8Array):void {const parameters=readDerChildren(this.imprint.algorithm.content)[1],expected=digest(this.imprint.algorithmOid,data,parameters);if(!equal(expected,this.imprint.hashedMessage))throw fail("TIMESTAMP_IMPRINT","timestamp does not match signature value");this.token.verify();}
}

export function parseTimestampToken(der:Uint8Array):CmsTimestamp {const signed=parseSignedData(der);if(signed.contentType!==CMS_OID.tstInfo)throw fail("UNSUPPORTED","CMS token does not contain TSTInfo");if(signed.detached)throw fail("MALFORMED","timestamp TSTInfo is detached");const fields=sequence(signed.content);if(fields.length<5||decodeBigInteger(fields[0]!)!==1n||fields[1]!.tag!==0x06||fields[2]!.tag!==0x30||fields[3]!.tag!==0x02||fields[4]!.tag!==0x18)throw fail("MALFORMED","malformed TSTInfo");const policy=decodeOid(fields[1]!),imprint=parseImprint(fields[2]!),serial=decodeBigInteger(fields[3]!),genTime=parseTime(fields[4]);if(genTime===undefined)throw fail("MALFORMED","malformed TSTInfo time");let index=5,accuracyMilliseconds=0,nonce:bigint|undefined;if(fields[index]?.tag===0x30){for(const item of readDerChildren(fields[index++]!.content)){if(item.tag===0x02)accuracyMilliseconds+=Number(decodeBigInteger(item))*1000;else if(item.tag===0x80)accuracyMilliseconds+=Number(decodeBigInteger(encodeDerElement(0x02,item.content)));else if(item.tag===0x81)accuracyMilliseconds+=Number(decodeBigInteger(encodeDerElement(0x02,item.content)))/1000;}}
  if(fields[index]?.tag===0x01)index+=1;if(fields[index]?.tag===0x02)nonce=decodeBigInteger(fields[index++]!);return new CmsTimestamp(genTime,accuracyMilliseconds,serial,policy,nonce,signed.certificates,signed.signers,signed,imprint,Uint8Array.from(der));}
function encodeDerElement(tag:number,content:Uint8Array):DerElement {const full=encodeDer(tag,content);return{tag,content,full,end:full.length};}

export function parseTimestampResponse(der:Uint8Array):CmsTimestamp {try{const fields=sequence(der),statusInfo=fields[0];if(statusInfo?.tag!==0x30)throw fail("MALFORMED","malformed timestamp response");const statusFields=readDerChildren(statusInfo.content),status=Number(decodeBigInteger(statusFields[0]!));if(status!==0&&status!==1)throw fail("TIMESTAMP_STATUS",`timestamp service returned status ${status}`);if(fields[1]?.tag!==0x30)throw fail("MALFORMED","timestamp response has no token");return parseTimestampToken(fields[1].full);}catch(error){if(error instanceof CmsError)throw error;throw fail("MALFORMED","malformed timestamp response");}}

export interface TimestampRequestOptions {readonly policy?:string;readonly nonce?:bigint;readonly requestCertificate?:boolean;}
export function createTimestampRequest(digestValue:Uint8Array,digestOid:string,options:TimestampRequestOptions={}):Uint8Array {if(digestValue.length===0||digestOid.length===0)throw fail("MALFORMED","timestamp request needs a digest");const imprint=encodeSequence(algorithm(digestOid),encodeOctetString(digestValue)),fields=[integer(1),imprint];if(options.policy!==undefined)fields.push(encodeOid(options.policy));if(options.nonce!==undefined)fields.push(encodeBigInteger(options.nonce));if(options.requestCertificate===true)fields.push(encodeDer(0x01,Uint8Array.of(0xff)));return encodeSequence(...fields);}
export interface TstInfoOptions {readonly digestValue:Uint8Array;readonly digestOid:string;readonly policy:string;readonly serialNumber:bigint;readonly genTime:Date;readonly nonce?:bigint;}
export function encodeTstInfo(options:TstInfoOptions):Uint8Array {if(options.digestValue.length===0||options.digestOid.length===0||options.policy.length===0)throw fail("MALFORMED","TSTInfo fields are incomplete");return encodeSequence(integer(1),encodeOid(options.policy),encodeSequence(algorithm(options.digestOid),encodeOctetString(options.digestValue)),encodeBigInteger(options.serialNumber),generalizedTime(options.genTime),...(options.nonce===undefined?[]:[encodeBigInteger(options.nonce)]));}
