import assert from "node:assert/strict";
import test from "node:test";
import { OID,encodeBitString,encodeDer,encodeOid,encodeSequence,encodeSubjectPublicKeyInfo } from "@gostcrypto/asn1";
import { CmsError,encryptCms,parseEnvelopedData } from "@gostcrypto/cms";
import { streebog256,streebog512 } from "@gostcrypto/hash";
import { createPrivateKey,encodePkixSignature,signDigest,TC26_PARAM_SET_256_B,TC26_PARAM_SET_512_C } from "@gostcrypto/signature";

const ascii=(value)=>new TextEncoder().encode(value),integer=(value)=>encodeDer(0x02,Uint8Array.of(value)),fill=(target)=>target.fill(1);
function certificate(privateKey,serial){const signatureOid=privateKey.curve.size===32?OID.signWithDigest256:OID.signWithDigest512,algorithm=encodeSequence(encodeOid(signatureOid)),name=encodeSequence(encodeDer(0x31,encodeSequence(encodeOid("2.5.4.3"),encodeDer(0x0c,ascii(`Recipient ${serial}`))))),validity=encodeSequence(encodeDer(0x17,ascii("260101000000Z")),encodeDer(0x17,ascii("360101000000Z"))),tbs=encodeSequence(encodeDer(0xa0,integer(2)),integer(serial),algorithm,name,validity,name,encodeSubjectPublicKeyInfo(privateKey.publicKey)),digest=privateKey.curve.size===32?streebog256(tbs):streebog512(tbs),signature=encodePkixSignature(privateKey.curve,signDigest(privateKey,digest,fill));return encodeSequence(tbs,algorithm,encodeBitString(signature));}

for(const [name,curve] of [["256",TC26_PARAM_SET_256_B],["512",TC26_PARAM_SET_512_C]])test(`CMS EnvelopedData round-trip with key meshing: ${name}`,()=>{const key=createPrivateKey(curve,123456789n),cert=certificate(key,1),content=Uint8Array.from({length:2050},(_,i)=>i*7&255),encoded=encryptCms(content,[cert],{fill}),enveloped=parseEnvelopedData(encoded);assert.equal(enveloped.recipients.length,1);assert.equal(enveloped.contentType,"1.2.840.113549.1.7.1");assert.deepEqual(enveloped.decrypt(key,cert),content);assert.deepEqual(enveloped.decrypt(key),content);});

test("CMS EnvelopedData supports multiple recipients and parameter sets",()=>{const keys=[3n,5n,7n].map((value)=>createPrivateKey(TC26_PARAM_SET_256_B,value)),certs=keys.map((key,index)=>certificate(key,index+1)),content=ascii("секрет для нескольких получателей");for(const parameterSetOid of[OID.cipherCryptoProA,OID.cipherCryptoProB,OID.cipherCryptoProC,OID.cipherCryptoProD,OID.cipherParamZ]){const enveloped=parseEnvelopedData(encryptCms(content,certs,{parameterSetOid,fill}));assert.equal(enveloped.recipients.length,3);for(let index=0;index<keys.length;index+=1)assert.deepEqual(enveloped.decrypt(keys[index],certs[index]),content);}});

test("CMS EnvelopedData rejects absent and foreign recipients",()=>{assert.throws(()=>encryptCms(ascii("x"),[]),(error)=>error instanceof CmsError&&error.code==="RECIPIENTS");const key=createPrivateKey(TC26_PARAM_SET_256_B,11n),cert=certificate(key,1),foreign=createPrivateKey(TC26_PARAM_SET_256_B,12n),enveloped=parseEnvelopedData(encryptCms(ascii("secret"),[cert],{fill}));assert.throws(()=>enveloped.decrypt(foreign,cert),(error)=>error instanceof CmsError&&error.code==="NO_RECIPIENT");assert.throws(()=>enveloped.decrypt(foreign),(error)=>error instanceof CmsError&&error.code==="NO_RECIPIENT");assert.throws(()=>parseEnvelopedData(new Uint8Array()),(error)=>error instanceof CmsError&&error.code==="MALFORMED");});
