import assert from "node:assert/strict";
import test from "node:test";
import { OID,encodeBitString,encodeDer,encodeOid,encodeSequence,encodeSubjectPublicKeyInfo } from "@gostcrypto/asn1";
import { streebog256 } from "@gostcrypto/hash";
import { marshalPfx,marshalPfxWithKey,parsePfx,parsePfxWithKey,PfxError } from "@gostcrypto/pfx";
import { createPrivateKey,encodePkixSignature,signDigest,TC26_PARAM_SET_256_B } from "@gostcrypto/signature";

const ascii=(value)=>new TextEncoder().encode(value),integer=(value)=>encodeDer(0x02,Uint8Array.of(value)),fill=(target)=>target.fill(1);
function certificate(privateKey,serial){const algorithm=encodeSequence(encodeOid(OID.signWithDigest256)),name=encodeSequence(encodeDer(0x31,encodeSequence(encodeOid("2.5.4.3"),encodeDer(0x0c,ascii(`PFX ${serial}`))))),validity=encodeSequence(encodeDer(0x17,ascii("260101000000Z")),encodeDer(0x17,ascii("360101000000Z"))),tbs=encodeSequence(encodeDer(0xa0,integer(2)),integer(serial),algorithm,name,validity,name,encodeSubjectPublicKeyInfo(privateKey.publicKey)),signature=encodePkixSignature(privateKey.curve,signDigest(privateKey,streebog256(tbs),fill));return encodeSequence(tbs,algorithm,encodeBitString(signature));}

test("R 50.1.112 key-protected PFX round-trips for multiple recipients",()=>{const transportedKey=createPrivateKey(TC26_PARAM_SET_256_B,3n),transportedCert=certificate(transportedKey,1),recipientA=createPrivateKey(TC26_PARAM_SET_256_B,5n),recipientB=createPrivateKey(TC26_PARAM_SET_256_B,7n),certA=certificate(recipientA,2),certB=certificate(recipientB,3),senderKey=createPrivateKey(TC26_PARAM_SET_256_B,11n),senderCert=certificate(senderKey,4),when=new Date("2026-09-12T10:00:00Z"),der=marshalPfxWithKey(transportedKey,[transportedCert],[certA,certB],{key:senderKey,certificate:senderCert},{localKeyId:Uint8Array.of(9,9,9),friendlyName:"Передача",signingTime:when,keyOptions:{masks:2},fillRandom:fill});
  for(const [key,cert] of [[recipientA,certA],[recipientB,certB]]){const container=parsePfxWithKey(der,{key,certificate:cert});assert.equal(container.hasMac,false);assert.equal(container.skippedSections,0);assert.equal(container.keys.length,1);assert.equal(container.keys[0].encrypted,false);assert.equal(container.keys[0].friendlyName,"Передача");assert.deepEqual(container.keys[0].localKeyId,Uint8Array.of(9,9,9));assert.deepEqual(container.keys[0].key,transportedKey);assert.deepEqual(container.certificateFor(container.keys[0])?.certificate,transportedCert);assert.deepEqual(container.signers,[senderCert]);}
  assert.throws(()=>parsePfx(der,ascii("password")),(error)=>error instanceof PfxError&&error.code==="UNSUPPORTED");
});

test("key-protected PFX rejects foreign recipients and tampering",()=>{const transported=createPrivateKey(TC26_PARAM_SET_256_B,13n),recipient=createPrivateKey(TC26_PARAM_SET_256_B,17n),sender=createPrivateKey(TC26_PARAM_SET_256_B,19n),recipientCert=certificate(recipient,2),der=marshalPfxWithKey(transported,[],[recipientCert],{key:sender,certificate:certificate(sender,3)},{fillRandom:fill}),foreign=createPrivateKey(TC26_PARAM_SET_256_B,23n);assert.throws(()=>parsePfxWithKey(der,{key:foreign,certificate:certificate(foreign,4)}));const changed=Uint8Array.from(der);changed[Math.floor(changed.length/2)]^=1;assert.throws(()=>parsePfxWithKey(changed,{key:recipient,certificate:recipientCert}));});

test("password and key PFX parsers remain distinct",()=>{const key=createPrivateKey(TC26_PARAM_SET_256_B,29n),recipient=createPrivateKey(TC26_PARAM_SET_256_B,31n),password=ascii("password"),passwordPfx=marshalPfx(key,[],password,{iterations:2,fillRandom:fill});assert.throws(()=>parsePfxWithKey(passwordPfx,{key:recipient,certificate:certificate(recipient,5)}),(error)=>error instanceof PfxError&&error.code==="UNSUPPORTED");assert.throws(()=>marshalPfxWithKey(key,[],[],{key,certificate:certificate(key,6)}),(error)=>error instanceof PfxError&&error.code==="NO_RECIPIENTS");});
